BEGIN;
CREATE TABLE public.roles (
  id text PRIMARY KEY CHECK (id IN ('cliente','mesera','cocina','caja','admin')),
  nombre text NOT NULL
);
INSERT INTO public.roles VALUES ('cliente','Cliente'),('mesera','Mesera'),('cocina','Cocina'),('caja','Caja'),('admin','Administrador');
CREATE TABLE public.perfiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre text NOT NULL DEFAULT '', apellido text NOT NULL DEFAULT '',
  telefono text NOT NULL DEFAULT '' CHECK (telefono = '' OR telefono ~ '^9[0-9]{8}$'),
  rol text NOT NULL DEFAULT 'cliente' REFERENCES public.roles(id),
  preferencias jsonb NOT NULL DEFAULT '{"notificacionesEmail":true,"notificacionesPromos":true}',
  creado_en timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.categorias (
  id text PRIMARY KEY, nombre text NOT NULL, descripcion text NOT NULL DEFAULT '', imagen text
);
CREATE TABLE public.productos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id text NOT NULL REFERENCES public.categorias(id),
  nombre text NOT NULL, descripcion text NOT NULL DEFAULT '',
  precio numeric(10,2) NOT NULL CHECK (precio >= 0), disponible boolean NOT NULL DEFAULT true, imagen text
);
CREATE TABLE public.mesas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero text NOT NULL UNIQUE, capacidad integer NOT NULL CHECK (capacidad > 0),
  forma text NOT NULL, zona text NOT NULL,
  estado text NOT NULL DEFAULT 'libre' CHECK (estado IN ('libre','ocupada','reservada'))
);
CREATE TABLE public.estados_pedido (id text PRIMARY KEY, nombre text NOT NULL);
INSERT INTO public.estados_pedido VALUES ('recibido','Recibido'),('preparacion','En preparación'),('listo','Listo'),('camino','En camino'),('entregado','Entregado'),('cancelado','Cancelado');
CREATE TABLE public.pedidos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), codigo text NOT NULL UNIQUE,
  cliente_id uuid REFERENCES public.perfiles(id), mesa_id bigint REFERENCES public.mesas(id),
  creado_por uuid NOT NULL REFERENCES public.perfiles(id),
  tipo text NOT NULL CHECK (tipo IN ('salon','delivery','recojo')),
  estado_id text NOT NULL DEFAULT 'recibido' REFERENCES public.estados_pedido(id),
  observaciones text NOT NULL DEFAULT '', entrega jsonb NOT NULL DEFAULT '{}',
  creado_en timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.detalles_pedido (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pedido_id uuid NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  producto_id bigint NOT NULL REFERENCES public.productos(id),
  cantidad integer NOT NULL CHECK (cantidad > 0),
  precio_unitario numeric(10,2) NOT NULL CHECK (precio_unitario >= 0)
);
CREATE TABLE public.pagos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id uuid NOT NULL REFERENCES public.pedidos(id),
  registrado_por uuid NOT NULL REFERENCES public.perfiles(id),
  monto numeric(10,2) NOT NULL CHECK (monto > 0),
  metodo text NOT NULL CHECK (metodo IN ('efectivo','tarjeta','yape','plin')),
  referencia text, creado_en timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX pedidos_cliente_idx ON public.pedidos(cliente_id);
CREATE INDEX detalles_pedido_idx ON public.detalles_pedido(pedido_id);
CREATE INDEX pagos_pedido_idx ON public.pagos(pedido_id);
COMMIT;
